eljuja/artikkelit/urls.py
from django.urls import path
from . import views

app_name = 'artikkelit'

urlpatterns = [
    path('uusi-artikkeli/', views.artikkeli_uusi, name="uusi-artikkeli"),
    path('export-myynti/', views.export_myynnit_to_excel, name='export_myynnit'),
]

eljuja/eljuja/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [ 
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('myynti/', views.myynti, name='myynti'),
    path('artikkelit/', include('artikkelit.urls')),
    path('users/', include('users.urls')),
    path('excel/', views.excel, name='excel'),
    path('get_asunnot/<int:taloyhtio_id>/', views.get_asunnot, name='get_asunnot'),
]

# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eljuja/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),

]

eljuja/templates/excel.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Master excelin käsittely</h1>
{% endblock %}

eljuja/templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    <h1>Aatelikorttelin katujuhlat</h1>
    <img src="media/Aatelikorttelin_katujuhlat_2025_posteri.png" alt="Katujuhlat posteri">
{% endblock %}

eljuja/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' type="text/css" media="screen" %}">
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
    <nav>
        <a href="/">
            <span role="img" src='media/Aatelikorttelin_katujuhlat_logo_punainen.jpg' aria-label="Home" title="Home">Pääsivu</span>
        </a> | 
        {% if user.is_authenticated %}
            <a href="/myynti">
                <span role="img" aria-label="Myynti" title="Myynti">Myynti</span>
            </a> | 
            {% if request.user.is_superuser %}
                <a href="{% url 'artikkelit:uusi-artikkeli' %}">
                    <span role="img" aria-label="Uusi Artikkeli" title="Uusi Artikkeli">Uusi</span>
                </a> | 
                <a href="{% url 'excel' %}">
                    <span role="img" aria-label="Excel" title="Excel">Excel</span>
                </a>
                {% endif %}
            <form class="logout" action="{% url 'users:logout' %}" method="post">
                {% csrf_token %} 
                <button class="logout-button" aria-label="User Logout" title="User Logout">Kirjaudu ulos</button>
            </form>
        {% else %}
            <a href="{% url 'users:login' %}">
                <span role="img" aria-label="Kirjaudu" title="Kirjaudu">Kirjaudu</span>
            </a>
        {% endif %}
    </nav>
    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

eljuja/templates/myynti.html
{% extends 'layout.html'%}
{% load get_item %}

{% block title %}
    Myynti
{% endblock %}
{% block content %}
    <head>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    
    <script>
        $(document).ready(function() {
            $('#taloyhtio').change(function() {
                var taloyhtio = $(this).val();

                //Tyhjennä ja estä asunto alasvetovalikko
                $('#asunto').empty().prop('disabled', true);
                $('#asunto').append('<option value="">-- Valitse asunto --</option>');
                if (taloyhtio) {
                    // tee AJAX pyyntö asuntojen hakemiseen 
                    $.ajax({
                        url: `/get_asunnot/${taloyhtio}/`,
                        type: 'GET',
                        dataType: 'json',
                        success: function(data) {
                            var asunnot = data.asunnot;
                            var asuntoDropdown = $('#asunto');

                            // Salli asuntovalinta
                            asuntoDropdown.prop('disabled', false);

                            // Täytä valinta haetulla datalla
                            $.each(asunnot, function(index, asunto) {
                                asuntoDropdown.append('<option value="' + asunto.id + '">' + asunto.nimi + '</option>');
                            });
                        },
                        error: function(error) {
                            console.log('Error fetching asuunot:', error);
                        }
                    });
                }
            });
        });
    </script>
    
    </head>
    <!-- Lomake lähettää dataa -->
    <form method="POST">  
        {% csrf_token %}
    <!-- Näytetään taloyhtiö- ja asuntoalinta alasetovalikot -->
    <label for="taloyhtio"></label>
    <select name='taloyhtio' id="taloyhtio" required>
        <option value=>-- Taloyhtio --</option>
        {% for taloyhtio in taloyhtiot %}
            <option value="{{ taloyhtio.id }}">{{ taloyhtio.nimi }}</option>
        {% endfor %}
    </select>
    <!-- <input value= name="taloyhtio"> -->
    
    <label for="asunto"></label>
    <select name='asunto' id="asunto" disabled required>
        <option value="" >-- Asunto --</option>
    </select>
        <br><br>
        <h2>Valitse ruokailuaika</h2>

        <!-- Ilmoitus jos ruoka-aikaa ei täytetty -->
        {% if aika_form.errors %}
            <div style="color: rgb(255, 217, 0);">
                {{ aika_form.errors.aika.0 }}
            </div>
        {% endif %}

        <!-- Näytetään radiovalinnat ja niiden viereen yhteenlasketut henkilömäärät kuhunkin ruokailuajankohtaan -->
        <label>
            <input type="radio" name="aika" value="1" {% if aika_form.data.aika == '1' %}checked{% endif %}> 16.30   ---    {{ passit_per_aika.1630 }}  / 50 hlöä
        </label><br>

        <label> 
            <input type="radio" name="aika" value="2" {% if aika_form.data.aika == '2' %}checked{% endif %}> 17.00   ---    {{ passit_per_aika.1700 }}  / 50 hlöä
        </label><br>

        <label>
            <input type="radio" name="aika" value="3" {% if aika_form.data.aika == '3' %}checked{% endif %}> 17.30   ---    {{ passit_per_aika.1730 }}  / 50 hlöä 
        </label><br>

        <label>
            <input type="radio" name="aika" value="4" {% if aika_form.data.aika == '4' %}checked{% endif %}> 18.00   ---    {{ passit_per_aika.1800 }}  / 50 hlöä
        </label><br>

        <br>
        <!-- Täytetään kpl-valintakentät uudelleen (ei tyhjennystä) jos Näytä summa -painiketta painettu -->
        {% for artikkeli in artikkelit %}
            
        {{ artikkeli.artikkeli }} {{ artikkeli.hinta }} €
        <input type="number" name="kpl_{{ artikkeli.id }}" min="0" step="1" value="{{ kpl_arvot|get_item:artikkeli.id|default:'0' }}">
        <br>
        {% endfor %}
        <br>
        <label for="kateismyynti">Käteismyynti</label>
        <input type="checkbox" name="kateismyynti" id="kateismyynti" >
        <br><br>
        <input type="submit" value="Näytä summa" name="nayta_summa">
        
        <b>Summa: {{ myyntisumma }} € </b><br><br>

        <input type="submit" value="Tallenna" name="tallenna">

    </form>
    <br>
    <h2>Myydyt tuotteet:</h2>
    <!-- Tulostetaan myydyt tuotteet -->
    {% for artikkeli, kpl in kokonaismyynti.items %}
        {{ artikkeli }}:  {{ kpl }}
            <br>
    {% endfor %}
{% endblock %}